services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_NAME: "taskdb"
      DB_USER: "postgres"
      DB_PASSWORD: "1234"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "taskdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
